#!/usr/bin/env python3
"""
calc_index.py  —  Compute a normalized-difference vegetation/moisture index.

Usage (mirrors gdal_calc.py interface used by the worker):
    calc_index.py -A bandA.tif [-B bandB.tif] [-C bandC.tif]
                  --calc FORMULA --outfile out.tif
                  [--type Float32] [--NoDataValue 9999] [--overwrite]

The FORMULA is a Python expression referencing numpy arrays A, B, C.
Nodata pixels in any input are propagated to the output as NoDataValue.
"""

import sys
import argparse
import numpy as np

try:
    from osgeo import gdal
    gdal.UseExceptions()
except ImportError:
    print("ERROR: osgeo.gdal not available", file=sys.stderr)
    sys.exit(1)


def read_band(path):
    """Open a single-band GeoTIFF and return (dataset, float32_array, nodata_mask)."""
    ds = gdal.Open(path, gdal.GA_ReadOnly)
    if ds is None:
        raise RuntimeError(f"Cannot open: {path}")
    band = ds.GetRasterBand(1)
    nodata_val = band.GetNoDataValue()
    data = band.ReadAsArray().astype(np.float32)
    mask = np.zeros(data.shape, dtype=bool)
    if nodata_val is not None:
        mask = np.isclose(data, nodata_val, atol=1e-3)

    # Format the range separately: a ":.3f" applied to the whole conditional
    # would try to format the "n/a" string when every pixel is masked, and
    # the diagnostic line itself would raise instead of reporting the problem.
    valid = data[~mask]
    if valid.size:
        vmin = f"{float(valid.min()):.3f}"
        vmax = f"{float(valid.max()):.3f}"
    else:
        vmin = vmax = "n/a"

    print(
        f"[calc_index] {path}: shape={data.shape} nodata={nodata_val} "
        f"valid={int(valid.size)} min={vmin} max={vmax}",
        file=sys.stderr,
    )
    return ds, data, mask


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-A", required=True)
    parser.add_argument("-B", default=None)
    parser.add_argument("-C", default=None)
    parser.add_argument("--calc", required=True)
    parser.add_argument("--outfile", required=True)
    parser.add_argument("--NoDataValue", type=float, default=9999.0)
    parser.add_argument("--type", default="Float32")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    nodata_out = args.NoDataValue

    ref_ds, A, maskA = read_band(args.A)
    combined_mask = maskA.copy()

    B = None
    if args.B:
        _, B, maskB = read_band(args.B)
        combined_mask |= maskB

    C = None
    if args.C:
        _, C, maskC = read_band(args.C)
        combined_mask |= maskC

    # eval() is safe here: --calc formulas are generated by the Go worker from
    # a hardcoded AllIndices() table (indices.go), never from user/external input.
    with np.errstate(divide="ignore", invalid="ignore"):
        result = eval(args.calc, {"numpy": np, "np": np, "A": A, "B": B, "C": C})  # noqa: S307

    result = np.where(combined_mask, nodata_out, result).astype(np.float32)

    valid = result[~combined_mask]
    if len(valid):
        print(
            f"[calc_index] output {args.outfile}: "
            f"valid={len(valid)} min={valid.min():.4f} max={valid.max():.4f} mean={valid.mean():.4f}",
            file=sys.stderr,
        )
    else:
        print(f"[calc_index] output {args.outfile}: NO VALID PIXELS", file=sys.stderr)

    driver = gdal.GetDriverByName("GTiff")
    out_ds = driver.Create(
        args.outfile,
        ref_ds.RasterXSize,
        ref_ds.RasterYSize,
        1,
        gdal.GDT_Float32,
    )
    out_ds.SetGeoTransform(ref_ds.GetGeoTransform())
    out_ds.SetProjection(ref_ds.GetProjection())
    out_band = out_ds.GetRasterBand(1)
    out_band.SetNoDataValue(nodata_out)
    out_band.WriteArray(result)
    out_band.FlushCache()
    out_ds = None
    print(f"[calc_index] wrote {args.outfile}", file=sys.stderr)


if __name__ == "__main__":
    main()
